task1/MyCompany.Resale/MyCompany.Resale.Presentation/Controllers/CityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using MyCompany.Resale.BusinessLogic.Provider.Interface;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using MyCompany.Resale.BusinessLogic.Description;
using CSharpFunctionalExtensions;
using MyCompany.Resale.Presentation.Models.CityViewModel;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MyCompany.Resale.Presentation.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CityController : Controller
    {
        private readonly ICityService _cityService;
        private readonly ILogger _logger;

        public CityController(
            IEventService eventService,
            ITicketService ticketService,
            IOrderService orderService,
            UserManager<User> userManager,
            ILogger<CityController> loggerFactory,
            ICityService cityService)
        {
            _cityService = cityService;
            _logger = loggerFactory;
        }


        [HttpGet]
        public IActionResult AllCities()
        {
            var cicies = _cityService.GetAllCities();
            if (cicies.IsFailure)
            {
                _logger.LogError(cicies.Error);
                return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = cicies.Error });
            }
            return View(cicies.Value);
        }

        [HttpGet]
        public IActionResult DeleteCity(int cityId)
        {
            var deleteResult = _cityService.GetCityById(cityId)
                .OnSuccess(c => _cityService.DeleteCity(c));

            if (deleteResult.IsFailure)
            {
                _logger.LogError(deleteResult.Error);
                return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = deleteResult.Error });
            }

            return RedirectToAction(nameof(CityController.AllCities));
        }

        [HttpGet]
        public IActionResult CraeteNewCity()
        {
            return View();
        }


        [HttpPost]
        public IActionResult CraeteNewCity(NewCityViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newCity = new City { Name = model.Name };

                var city = _cityService.GetCityByName(model.Name);
                if (city.IsSuccess)
                {
                    _logger.LogError("We have such City in DB");
                    return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = "We have such City in DB" });
                }

                var addResult = _cityService.AddCity(newCity);

                if (addResult.IsFailure)
                {
                    _logger.LogError(addResult.Error);
                    return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = addResult.Error });
                }

                return RedirectToAction(nameof(CityController.AllCities));
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult EditCity(int cityId)
        {
            var city = _cityService.GetCityById(cityId);
            if (city.IsFailure)
            {
                _logger.LogError(city.Error);
                return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = city.Error });
            }
            var model = new NewCityViewModel
            {
                Id = city.Value.Id,
                Name = city.Value.Name
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult EditCity(int cityId, NewCityViewModel model)
        {
            var city = _cityService.GetCityById(cityId);
            if (city.IsFailure)
            {
                _logger.LogError(city.Error);
                return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = city.Error });
            }
            city.Value.Name = model.Name;
            var updateResult = _cityService.UpdateCity(city.Value);
            if (updateResult.IsFailure)
            {
                _logger.LogError(updateResult.Error);
                return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = updateResult.Error });
            }
            return RedirectToAction(nameof(CityController.AllCities));
        }
    }
}

task1/MyCompany.Resale/MyCompany.Resale.Presentation/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using MyCompany.Resale.BusinessLogic.Provider.Interface;
using MyCompany.Resale.BusinessLogic.Description;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MyCompany.Resale.Presentation.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IOrderService _orderService;

        public OrdersController(IEventService eventService, ITicketService ticketService, IOrderService orderService,
            UserManager<User> userManager)
        {
            _orderService = orderService;
            _userManager = userManager;
        }

        /// <summary>
        /// Display all orders curren authorize user
        /// </summary>
        /// <returns></returns>
        public IActionResult Orders()
        {
            var user = _userManager.FindByNameAsync(User.Identity.Name).Result;

            if (user != null)
            {
                var orders = _orderService.GetOrdersByUserId(user.Id);
                if (orders.IsFailure)
                {
                    ViewBag.Errors = orders.Error;
                }
                return View(orders.Value);
            }

            return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = "This user isn't present in db" });
        }
    }
}

task1/MyCompany.Resale/MyCompany.Resale.Presentation/Controllers/VenueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using MyCompany.Resale.BusinessLogic.Provider.Interface;
using Microsoft.Extensions.Logging;
using CSharpFunctionalExtensions;
using MyCompany.Resale.Presentation.Models.VenueViewModels;
using MyCompany.Resale.BusinessLogic.Description;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MyCompany.Resale.Presentation.Controllers
{
    [Authorize(Roles = "Admin")]
    public class VenueController : Controller
    {
        private readonly ICityService _cityService;
        private readonly IVenueService _venueService;
        private readonly ILogger _logger;

        public VenueController(
            ILogger<VenueController> loggerFactory,
            ICityService cityService,
            IVenueService venueService)
        {
            _cityService = cityService;
            _venueService = venueService;
            _logger = loggerFactory;
        }
        
        [HttpGet]
        public IActionResult AllVenue()
        {
            var venues = _venueService.GetAllVenues();
            if (venues.IsFailure)
            {
                _logger.LogError(venues.Error);
                return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = venues.Error });
            }

            return View(venues.Value);
        }


        [HttpGet]
        public IActionResult DeleteVenue(int venueId)
        {
            var deleteResult = _venueService.GetVenueById(venueId)
                .OnSuccess(v => _venueService.DeleteVenue(v));

            if (deleteResult.IsFailure)
            {
                _logger.LogError(deleteResult.Error);
                return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = deleteResult.Error });
            }

            return RedirectToAction(nameof(VenueController.AllVenue));
        }

        [HttpGet]
        public IActionResult CreateNewVenue()
        {
            var cities = _cityService.GetAllCities();
            if (cities.IsFailure)
            {
                _logger.LogError(cities.Error);
                return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = cities.Error });
            }

            var model = new NewVenueViewModel
            {
                Cities = cities.Value
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult CreateNewVenue(NewVenueViewModel model)
        {
            if (ModelState.IsValid)
            {
                var city = _cityService.GetCityById(model.CityId);
                if (city.IsFailure)
                {
                    _logger.LogError(city.Error);
                    return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = city.Error });
                }

                var tVenue = _venueService.GetVenueByName(model.VenueName);
                if (tVenue.IsSuccess)
                {
                    _logger.LogError("We have such City in DB");
                    return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = "We have such City in DB" });
                }

                var venue = new Venue { Name = model.VenueName, Address = model.Address, City = city.Value };

                var addResult = _venueService.AddVenue(venue);
                if (addResult.IsFailure)
                {
                    _logger.LogError(tVenue.Error);
                    return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = tVenue.Error });
                }

                return RedirectToAction(nameof(VenueController.AllVenue));
            }

            var cities = _cityService.GetAllCities();
            if (cities.IsFailure)
            {
                _logger.LogError(cities.Error);
                return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = cities.Error });
            }
            model.Cities = cities.Value;

            return View(model);
        }

        [HttpGet]
        public IActionResult EditVenue(int venueId)
        {
            var venue = _venueService.GetVenueById(venueId);
            var cities = _cityService.GetAllCities();

            var commonResult = Result.Combine(venue, cities);

            if (commonResult.IsFailure)
            {
                _logger.LogError(commonResult.Error);
                return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = commonResult.Error });
            }

            var model = new NewVenueViewModel
            {
                Address = venue.Value.Address,
                VenueName = venue.Value.Name,
                CityId = venue.Value.City.Id,
                CityName = venue.Value.City.Name,
                VenueId = venue.Value.Id,
                Cities = cities.Value
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult EditVenue(int venueId, NewVenueViewModel model)
        {
            if (ModelState.IsValid)
            {
                var venue = _venueService.GetVenueById(venueId);
                var city = _cityService.GetCityById(model.CityId);

                var commonResult = Result.Combine(venue, city);
                if (commonResult.IsFailure)
                {
                    _logger.LogError(commonResult.Error);
                    return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = commonResult.Error });
                }

                venue.Value.Address = model.Address;
                venue.Value.Name = model.VenueName;
                venue.Value.City = city.Value;

                var updateResult = _venueService.UpdateVenue(venue.Value);
                if (updateResult.IsFailure)
                {
                    _logger.LogError(updateResult.Error);
                    return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = updateResult.Error });
                }

                return RedirectToAction(nameof(VenueController.AllVenue));
            }

            var cities = _cityService.GetAllCities();
            if (cities.IsFailure)
            {
                _logger.LogError(cities.Error);
                return RedirectToAction(nameof(ErrorController.ShowError), "Error", new { error = cities.Error });
            }

            model.Cities = cities.Value;
            return View(model);
        }
    }
}

task1/MyCompany.Resale/MyCompany.Resale.Presentation/Views/Shared/_AdminPanelPartial.cshtml
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@using Microsoft.AspNetCore.Identity
@using MyCompany.Resale.Presentation.Models

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager


@if (User.IsInRole("Admin"))
{
    <form asp-area="" asp-controller="Account" asp-action="LogOff" method="post" id="logoutForm" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li><a asp-controller="Account" asp-action="AllUsers">@Localizer["All Users"]</a></li>
            <li><a asp-controller="City" asp-action="AllCities">@Localizer["All Cities"]</a></li>
            <li><a asp-controller="Venue" asp-action="AllVenue">@Localizer["All Venue"]</a></li>
        </ul>
    </form>
}

task1/MyCompany.Resale/MyCompany.Resale.Presentation/Views/Shared/_Layout.cshtml
@using System.Globalization
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyCompany.Resale</title>
    <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StyleSheet1.css" asp-append-version="true" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">@Localizer["Toggle navigation"]</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Events" asp-action="Index" class="navbar-brand">MyCompany.Resale</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   <li><a asp-controller="Events" asp-action="Index">@Localizer["Events"]</a></li>
                   <li><a asp-controller="Tickets" asp-action="Tickets">@Localizer["Tickets"]</a></li>
                   <li><a asp-controller="Orders" asp-action="Orders">@Localizer["Orders"]</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <div class="col-md-6">
                    <p>&copy; 2017 - MyCompany.Resale</p>
                </div>
                <div class="col-md-6 text-right">
                    @await Html.PartialAsync("_SelectLanguagePartial")
                </div>
            </div>
        </footer>
    </div>
    <script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

task1/MyCompany.Resale/MyCompany.Resale.Presentation/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}
<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path" method="post" class="form-horizontal" role="form">
        @Localizer["Language:"] <select name="culture" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
    </form>
</div>